name: Run eslint, prettier and test checking

on:
  push:
    branches:
      - develop
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn install
      - name: ESLint and Prettier Check
        run: |
          yarn lint
          yarn prettier
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test
